version: '3'

services:
  web:
    restart: on-failure
    build: .
    command: python blackjack_backend/manage.py runserver 0.0.0.0:8000
    image: ${DOCKERID}/blackjack-backend
    volumes:
      - .:/blackjack_backend
    ports:
      - "8000:8000"
    depends_on:
      - db